### ISSUE TITLE
page_547.rb

### ISSUE THREAD

**Issue by denys-medynskyi** [T-Dnzt/Master-Ruby-Web-APIs#5]
Field in [migration](https://gist.github.com/skrypalyk/bce05d3ba6423eec266b478cf8c62b8d) is called `charger_id`
Field in [model](https://gist.github.com/skrypalyk/00bb1dcbde5e77a1b954a8733acb8ff9) is called `charge_id`.
Which one is correct ?

**Comment by T-Dnzt** [comment]
It should be `charge_id`, thanks for reporting it. Fixing it now and it will be in the next edition of the book.
