### ISSUE TITLE
Book, publisher association test pass?

### ISSUE THREAD

**Issue by briancolfer** [T-Dnzt/Master-Ruby-Web-APIs#6]
Should it fail not pass?

“Let’s run rspec to see the new tests fail.

rspec spec/models/book_spec.rb
Success (GREEN)”

Excerpt From: Denizet, Thibault. “Master Ruby Web APIs.” Softcover. iBooks. 
This material may be protected by copyright.

**Comment by T-Dnzt** [comment]
They should actually pass. I will fix the issue, it will be in the next edition of the book!
